name: Build and Promote Image

on:
  push:
    branches:
      - main
    paths:
      - 'packer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure HCP Credentials
        id: hcp-auth
        uses: hashicorp/hcp-auth-action@v0.1.0
        with:
          workload_identity_provider: ${{ secrets.HCP_WIP }}
          export_environment_variables: true
      
      - name: Install HCP CLI
        uses: hashicorp/hcp-setup-action@v0.1.0
        with:
          version: 'latest'
      
      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.14.2'
      
      - name: Build Packer Image
        working-directory: ./packer
        run: |
          packer init .
          packer build -var "channel=staging" template.pkr.hcl
      
      - name: Get Latest Iteration ID
        id: get-iteration
        run: |
          ITERATION_ID=$(hcp packer iterations list \
            --bucket-name my-bucket \
            --format json | jq -r '.[0].id')
          echo "iteration_id=$ITERATION_ID" >> $GITHUB_OUTPUT
      
      - name: Promote to Staging Channel
        uses: Timotej979/hcp-packer-promote-to-channel-action@v0.1
        with:
          hcp_cred_file: ${{ steps.hcp-auth.outputs.credentials_file_path }}
          hcp_cli_version: 'latest'
          iteration_id: ${{ steps.get-iteration.outputs.iteration_id }}
          channel: 'staging'
          bucket_name: 'my-bucket'

